spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
app:
  startup:
    seed: false
